{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.1.0/k2o-1.1.0.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.1.0.jar",
          "url": "k2o-jvm-1.1.0.jar",
          "size": 67665,
          "sha512": "6fe2ce8ca08debaf7d1d04da831bd1ffa8554b910e56cecebae83b12cd34da352586759e5e29e26dd480b73167ed456277c8be9028d37427b22a77a1461d7323",
          "sha256": "df5d29187cae46fab4a8cde9bd79aba69f99151722569733b9a73fcd7dfe5a74",
          "sha1": "df226d22ed8cca051005ca3a1d6aa9767b8248b2",
          "md5": "c661d267ecb14b574d73f36839c92579"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.1.0.jar",
          "url": "k2o-jvm-1.1.0.jar",
          "size": 67665,
          "sha512": "6fe2ce8ca08debaf7d1d04da831bd1ffa8554b910e56cecebae83b12cd34da352586759e5e29e26dd480b73167ed456277c8be9028d37427b22a77a1461d7323",
          "sha256": "df5d29187cae46fab4a8cde9bd79aba69f99151722569733b9a73fcd7dfe5a74",
          "sha1": "df226d22ed8cca051005ca3a1d6aa9767b8248b2",
          "md5": "c661d267ecb14b574d73f36839c92579"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.1.0-sources.jar",
          "url": "k2o-jvm-1.1.0-sources.jar",
          "size": 23711,
          "sha512": "cb145b6ca60c60315e697c1502e701ecb7b896c0b8a77f1ead1501688b4d5b866e60f49adbbbdcdd82dd7c44ab48720ff49faab915cf99b6b65f7a446b494b02",
          "sha256": "8180db02ce2cfe54afe2e97bcde5303a435d86831c24a80be3bedc8edc239cf6",
          "sha1": "ba09e240ce5a71b367430d98aff45440cc0ff784",
          "md5": "dbb47714180de66629ab3286a214b829"
        }
      ]
    }
  ]
}
