{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.4.0/k2o-1.4.0.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-macosArm64Main-1.4.0.klib",
          "url": "k2o-macosarm64-1.4.0.klib",
          "size": 113340,
          "sha512": "ffde65486b96b239e79ba7c256389d6bd5355d67e29e2bf43e2955fe0e9efc958d54c3ffe5df6d1d4be2fde017ec6a14db3a1145b53ac0db94e3d84c8cb3ae0f",
          "sha256": "bc5439599c9213dd5d7e076a9ec6043e3e74585a9e3272024cd5a33cee55a54b",
          "sha1": "85d6489e9deb98345971696c2551095178d49073",
          "md5": "bd59badda8c0b806a71060b34ef199fa"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "k2o-macosarm64-1.4.0-sources.jar",
          "url": "k2o-macosarm64-1.4.0-sources.jar",
          "size": 41915,
          "sha512": "ee163ed3b88242eb0e372a692330bffc42754ba53c46d0fea41b60c6defd09a0bb2fd9be6a3683266d32429bcbf2e337dbaef310553b90fa8335d4646e9b488b",
          "sha256": "736adec3a4b491d793d0f670a002d524f8ff17507faf8fb6977a8ab03b2fb524",
          "sha1": "74a7a7772585b495a8ca77053c4a0b37b0049977",
          "md5": "ee0d1933fd465691ea5f81f72e24b2b2"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-1.4.0.kotlin_resources.zip",
          "url": "k2o-macosarm64-1.4.0-kotlin_resources.kotlin_resources.zip",
          "size": 320,
          "sha512": "aa5d83657f2f79a5740e02986572f396b1f22edde69d2635ac35bd203eb05704543333a69b22a06a775f40c6180667ab2ffe270cbef5313fab826a8efda6e38e",
          "sha256": "1a2ce1e84034808990a1d6fc181b3906239ef554bffdee1db4a527a4309d522d",
          "sha1": "4160abdb49e240bfe35779c2416e4a7d99fc1ee2",
          "md5": "83064256c0773dff74573c1f3e96feaf"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-macosarm64-1.4.0-metadata.jar",
          "url": "k2o-macosarm64-1.4.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
