{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-metadata-1.3.1-SNAPSHOT.jar",
          "url": "k2o-1.3.1-SNAPSHOT.jar",
          "size": 18438,
          "sha512": "80758f9c7da2fcd0049ca12020c4d90ef94fe57be4cd8c1b8b4581ca6367028f0e673ace3aca946da188371c48785d713e65521d2a4d11b122ec0f48fc7a2def",
          "sha256": "9a39e1e20fedcf65ba59a56c8bff3c7bb8bf6e1b0af56b3131dfb752aefecc25",
          "sha1": "60d282a435cd82f286fe47f9efc1bb991d0f5c82",
          "md5": "699edaed488af4cbe139780aafa9b8dc"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "k2o-kotlin-1.3.1-SNAPSHOT-sources.jar",
          "url": "k2o-1.3.1-SNAPSHOT-sources.jar",
          "size": 38324,
          "sha512": "577be50388d6a3a55a89ada481578fbb6835f4a1edd2bd511500006591398884f9cbfc3395d1af191f28e3ceacfafd7a09a38d36e495e546b26b4c5e16b5e362",
          "sha256": "2f409b7511b7be898bac9f08e6d9581b4f2a1e2f6fba280e10f14312c2410edf",
          "sha1": "0ba8aa285551287145eb12ac56206c7426db2f9c",
          "md5": "acfcb8081a2ab410bb532a74855fdca4"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../k2o-jvm/1.3.1-SNAPSHOT/k2o-jvm-1.3.1-SNAPSHOT.module",
        "group": "org.jraf.k2o",
        "module": "k2o-jvm",
        "version": "1.3.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../k2o-jvm/1.3.1-SNAPSHOT/k2o-jvm-1.3.1-SNAPSHOT.module",
        "group": "org.jraf.k2o",
        "module": "k2o-jvm",
        "version": "1.3.1-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../k2o-jvm/1.3.1-SNAPSHOT/k2o-jvm-1.3.1-SNAPSHOT.module",
        "group": "org.jraf.k2o",
        "module": "k2o-jvm",
        "version": "1.3.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.1-SNAPSHOT/k2o-macosarm64-1.3.1-SNAPSHOT.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.1-SNAPSHOT/k2o-macosarm64-1.3.1-SNAPSHOT.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.1-SNAPSHOT/k2o-macosarm64-1.3.1-SNAPSHOT.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.1-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.1-SNAPSHOT/k2o-macosarm64-1.3.1-SNAPSHOT.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.1-SNAPSHOT"
      }
    }
  ]
}
