{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-metadata-1.3.0.jar",
          "url": "k2o-1.3.0.jar",
          "size": 18438,
          "sha512": "80758f9c7da2fcd0049ca12020c4d90ef94fe57be4cd8c1b8b4581ca6367028f0e673ace3aca946da188371c48785d713e65521d2a4d11b122ec0f48fc7a2def",
          "sha256": "9a39e1e20fedcf65ba59a56c8bff3c7bb8bf6e1b0af56b3131dfb752aefecc25",
          "sha1": "60d282a435cd82f286fe47f9efc1bb991d0f5c82",
          "md5": "699edaed488af4cbe139780aafa9b8dc"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "k2o-kotlin-1.3.0-sources.jar",
          "url": "k2o-1.3.0-sources.jar",
          "size": 38316,
          "sha512": "c4b9412ae30a3808e5627d9e468ea579e175449d285d90ea25be87f739472a4bdfbeb752d62638156231d4908c15aa29097982c1778f356c43d7f93b71ef35de",
          "sha256": "b3708c46270e288cf203dfe3e4bb55f435ecae4fe491b81567546d5ddfa2816b",
          "sha1": "9ae72deecac69b69c4a7196ec3d01ef2383eed33",
          "md5": "d9a076e01dec3b76a144436dad1783e9"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../k2o-jvm/1.3.0/k2o-jvm-1.3.0.module",
        "group": "org.jraf.k2o",
        "module": "k2o-jvm",
        "version": "1.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../k2o-jvm/1.3.0/k2o-jvm-1.3.0.module",
        "group": "org.jraf.k2o",
        "module": "k2o-jvm",
        "version": "1.3.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../k2o-jvm/1.3.0/k2o-jvm-1.3.0.module",
        "group": "org.jraf.k2o",
        "module": "k2o-jvm",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.0/k2o-macosarm64-1.3.0.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.0/k2o-macosarm64-1.3.0.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.0/k2o-macosarm64-1.3.0.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.0/k2o-macosarm64-1.3.0.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.0"
      }
    }
  ]
}
