{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.2.1/k2o-1.2.1.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.2.1.jar",
          "url": "k2o-jvm-1.2.1.jar",
          "size": 103205,
          "sha512": "63c3f55082c11b66bdb7079e976b35305753c2c222aa6ea3d9dc49f888cd3d61d3640a25aabe2ef3c9bcc84abf20b728a92ce69e271c2c49d309f52c5cd3a75b",
          "sha256": "c2a29546420f1cab341dd8f4ba4ff4975dfc7c1082936872b323d115aca27f8f",
          "sha1": "1a09ce11b26988a01ddb1cf983c0486fc7f5b94e",
          "md5": "96b550dfa5ffdaa06496f1891f22bd99"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.2.1.jar",
          "url": "k2o-jvm-1.2.1.jar",
          "size": 103205,
          "sha512": "63c3f55082c11b66bdb7079e976b35305753c2c222aa6ea3d9dc49f888cd3d61d3640a25aabe2ef3c9bcc84abf20b728a92ce69e271c2c49d309f52c5cd3a75b",
          "sha256": "c2a29546420f1cab341dd8f4ba4ff4975dfc7c1082936872b323d115aca27f8f",
          "sha1": "1a09ce11b26988a01ddb1cf983c0486fc7f5b94e",
          "md5": "96b550dfa5ffdaa06496f1891f22bd99"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.2.1-sources.jar",
          "url": "k2o-jvm-1.2.1-sources.jar",
          "size": 25702,
          "sha512": "314899a2e4b2ab127b2313dcd04be49e9617b3d10a92c79181b9d930cb77d662f725971e9f83d10d043f5a37688326bb24647859a759d7ded501b28e375910d5",
          "sha256": "f0cc45f8f58f09d527ee46fcaee0ec7ed19ad2eed6f980d6ba4332f5717bc68d",
          "sha1": "c2d413ef0079acfb412bfe09076e4d52bb5650bb",
          "md5": "7b81fcc39e8e6c25ef052084ba93e82d"
        }
      ]
    }
  ]
}
