{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.4.0-SNAPSHOT/k2o-1.4.0-SNAPSHOT.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.4.0-SNAPSHOT.jar",
          "url": "k2o-jvm-1.4.0-SNAPSHOT.jar",
          "size": 115278,
          "sha512": "d8500e029d1b0e506f818008e9b148534aea55a2f9fdba4162096aaff77d8435e4df7b6d223395144e4a195d30489b5e7fb9b1746b7c3c2bae4d1cf630bc4b1a",
          "sha256": "35e9170ca0b54eabe33f287e170275cf6a9e2d426ad08395fa2b9c597ec80256",
          "sha1": "d03e76c0eceb17d28480696005614c5ce02e687f",
          "md5": "9d774c0e476878b4b9f2852ea146765a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.4.0-SNAPSHOT.jar",
          "url": "k2o-jvm-1.4.0-SNAPSHOT.jar",
          "size": 115278,
          "sha512": "d8500e029d1b0e506f818008e9b148534aea55a2f9fdba4162096aaff77d8435e4df7b6d223395144e4a195d30489b5e7fb9b1746b7c3c2bae4d1cf630bc4b1a",
          "sha256": "35e9170ca0b54eabe33f287e170275cf6a9e2d426ad08395fa2b9c597ec80256",
          "sha1": "d03e76c0eceb17d28480696005614c5ce02e687f",
          "md5": "9d774c0e476878b4b9f2852ea146765a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.4.0-SNAPSHOT-sources.jar",
          "url": "k2o-jvm-1.4.0-SNAPSHOT-sources.jar",
          "size": 41923,
          "sha512": "bb3dceb9065cdd8d758423b4af68beaa8c40bac2f4adfcf0cbbc9967bbded8cce4d44d73ef24b71ce1ad30b3aee004d95f332a4d124209437b1d791983124c65",
          "sha256": "80310132259d65231a599e6f8116f4c03a205a8d20f4343b1e5da3acb1849b64",
          "sha1": "ee5654ba4966292cb84269b1a74b4119ada4217a",
          "md5": "3211e5c04423d62e880a1551f10d6dd1"
        }
      ]
    }
  ]
}
