{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.2.0/k2o-1.2.0.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.2.0.jar",
          "url": "k2o-jvm-1.2.0.jar",
          "size": 69751,
          "sha512": "39399351a3ca23d302d7c6ecaac58754bfe227116c198d0a54af803c6363a123c7bfd4f1060d44e3ee3a9a28a06d9521a61958aad198b23b2afb1d02e0a78a27",
          "sha256": "d7c1106dee2180ba34e2f0db590659cb680fe5b9acec2780b0e62277f6680c4c",
          "sha1": "fc42cdd3efad28ada16f46ee2b2c688b3cb1ae96",
          "md5": "b0564779540e1fa5ae663cdd371fced0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.2.0.jar",
          "url": "k2o-jvm-1.2.0.jar",
          "size": 69751,
          "sha512": "39399351a3ca23d302d7c6ecaac58754bfe227116c198d0a54af803c6363a123c7bfd4f1060d44e3ee3a9a28a06d9521a61958aad198b23b2afb1d02e0a78a27",
          "sha256": "d7c1106dee2180ba34e2f0db590659cb680fe5b9acec2780b0e62277f6680c4c",
          "sha1": "fc42cdd3efad28ada16f46ee2b2c688b3cb1ae96",
          "md5": "b0564779540e1fa5ae663cdd371fced0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.2.0-sources.jar",
          "url": "k2o-jvm-1.2.0-sources.jar",
          "size": 24492,
          "sha512": "e63b07ebd8594fa967cb9db27828816fce232242869769f35d239d33d4240d2da09e7a753f9ecc0a1dede954092d570a155fe83f682bbb980a4d96596a9d34b4",
          "sha256": "5dc02dc719cf8ec06c1218afb50c49e2f2fc372dcf2c7f6b1b4da3fe61038d3e",
          "sha1": "60b7305c61b3a3ca088a87f43c396da22b6780f3",
          "md5": "e12983602d0d668123758d55df92677d"
        }
      ]
    }
  ]
}
