{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.2.1-SNAPSHOT/k2o-1.2.1-SNAPSHOT.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.2.1-SNAPSHOT.jar",
          "url": "k2o-jvm-1.2.1-SNAPSHOT.jar",
          "size": 103215,
          "sha512": "b0a5334bfa685d5dd7bea1a13445169b94c94478689b927a950a94f8eec71b6b8af6ab06c7c352ac03e0ca175bedb6941627f66d362307b6f0fa3a606baddb1c",
          "sha256": "0f1249e269aa613f6e5a5961514a27151d505482900d26a70834968ebd1ba518",
          "sha1": "4f792c34efd76682e798963b6341f1a4b5afdb30",
          "md5": "ffd1bd7b0aadce2f3129a19b5df6557c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.2.1-SNAPSHOT.jar",
          "url": "k2o-jvm-1.2.1-SNAPSHOT.jar",
          "size": 103215,
          "sha512": "b0a5334bfa685d5dd7bea1a13445169b94c94478689b927a950a94f8eec71b6b8af6ab06c7c352ac03e0ca175bedb6941627f66d362307b6f0fa3a606baddb1c",
          "sha256": "0f1249e269aa613f6e5a5961514a27151d505482900d26a70834968ebd1ba518",
          "sha1": "4f792c34efd76682e798963b6341f1a4b5afdb30",
          "md5": "ffd1bd7b0aadce2f3129a19b5df6557c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.2.1-SNAPSHOT-sources.jar",
          "url": "k2o-jvm-1.2.1-SNAPSHOT-sources.jar",
          "size": 25709,
          "sha512": "5dfcaeeee9f81f8a022bd37e3a53cd5202b474cbb4d2778c87c7957058d0ac7473d082c083369e0eb6ec4aa91e3d7d39363ac1c9762cfc8653a6921134497046",
          "sha256": "f8368a1b6559d4db00741f9ec591ce0c42b317a68dfd18da85695ce414e1c276",
          "sha1": "c4936377efe9ea6bc4bcefeb5c1f216d8a7c2297",
          "md5": "75c1bfe244471d06b3d0c61f9974aa30"
        }
      ]
    }
  ]
}
