{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.2.1-SNAPSHOT/k2o-1.2.1-SNAPSHOT.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.2.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.2.1-SNAPSHOT.jar",
          "url": "k2o-jvm-1.2.1-SNAPSHOT.jar",
          "size": 69760,
          "sha512": "13f31f3b3e13740d0d798743a3c4da80628beba303b2281dcfaa008a4a20256e0c4f033335c984b57b86b919db927922b9f7b298c3999a5493198ebab968adfd",
          "sha256": "611e76363195838f5ab20feac8f5ca2b14059b18da2d55b299d4fd39334dd103",
          "sha1": "c2e8b8ae24aecbcdea1fc0b62aa3885f466a8d9a",
          "md5": "53425e20306fd66207e0a258a5615f5d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.2.1-SNAPSHOT.jar",
          "url": "k2o-jvm-1.2.1-SNAPSHOT.jar",
          "size": 69760,
          "sha512": "13f31f3b3e13740d0d798743a3c4da80628beba303b2281dcfaa008a4a20256e0c4f033335c984b57b86b919db927922b9f7b298c3999a5493198ebab968adfd",
          "sha256": "611e76363195838f5ab20feac8f5ca2b14059b18da2d55b299d4fd39334dd103",
          "sha1": "c2e8b8ae24aecbcdea1fc0b62aa3885f466a8d9a",
          "md5": "53425e20306fd66207e0a258a5615f5d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.2.1-SNAPSHOT-sources.jar",
          "url": "k2o-jvm-1.2.1-SNAPSHOT-sources.jar",
          "size": 24499,
          "sha512": "d8c0d9bff816b70122c6eccdd3f7af0ee554ea021d53fdbf4363df6d1a51b0e44f540f090316137a8434f2770ed9c3f48939f13b180feec55db604eeded256f6",
          "sha256": "332db5410ccb5288f98314d38cb61278effe34dd71dc2d2081ddc960f9058efa",
          "sha1": "780c81203f4b046f2654b016f6100a7c2707401b",
          "md5": "25da5bcc3333d6f95c6522aa67f7e140"
        }
      ]
    }
  ]
}
