{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.4.0/k2o-1.4.0.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.4.0.jar",
          "url": "k2o-jvm-1.4.0.jar",
          "size": 115269,
          "sha512": "48016ae488f6ed398a0590fd739fbf09d7df0dc4b2caadb66f989776dada34be38a958c0a09804e8532649f0fc58fbd2ca5cb09b255d30a675c96e1ef7ed0b63",
          "sha256": "78b0e0eb57fe63247a85e3dcab6a796cd047346058d9326f1c744986ea04f5dc",
          "sha1": "ea8b614d34de0795e09e8bd56e1875a1dc12715d",
          "md5": "52024025ddfe662214f546e7ce4e21f2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.4.0.jar",
          "url": "k2o-jvm-1.4.0.jar",
          "size": 115269,
          "sha512": "48016ae488f6ed398a0590fd739fbf09d7df0dc4b2caadb66f989776dada34be38a958c0a09804e8532649f0fc58fbd2ca5cb09b255d30a675c96e1ef7ed0b63",
          "sha256": "78b0e0eb57fe63247a85e3dcab6a796cd047346058d9326f1c744986ea04f5dc",
          "sha1": "ea8b614d34de0795e09e8bd56e1875a1dc12715d",
          "md5": "52024025ddfe662214f546e7ce4e21f2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.4.0-sources.jar",
          "url": "k2o-jvm-1.4.0-sources.jar",
          "size": 41915,
          "sha512": "ee163ed3b88242eb0e372a692330bffc42754ba53c46d0fea41b60c6defd09a0bb2fd9be6a3683266d32429bcbf2e337dbaef310553b90fa8335d4646e9b488b",
          "sha256": "736adec3a4b491d793d0f670a002d524f8ff17507faf8fb6977a8ab03b2fb524",
          "sha1": "74a7a7772585b495a8ca77053c4a0b37b0049977",
          "md5": "ee0d1933fd465691ea5f81f72e24b2b2"
        }
      ]
    }
  ]
}
