{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.3.0/k2o-1.3.0.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.3.0.jar",
          "url": "k2o-jvm-1.3.0.jar",
          "size": 102678,
          "sha512": "907d3eada59cd9555f506324e733fe9a44670a749dd7b0b91de512e01fa5202708698e0188fdfc6ac5e578f7cd9617304d03f99a7ee8a31e874270d067917042",
          "sha256": "b62f505922def8ab07ebbd36b8d047403357053d427df0e0704a1647eede8715",
          "sha1": "65ba12a4bfd28967813b089666af6f86ce5d7b43",
          "md5": "13bbac70df7da2c79b553a771286c857"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.3.0.jar",
          "url": "k2o-jvm-1.3.0.jar",
          "size": 102678,
          "sha512": "907d3eada59cd9555f506324e733fe9a44670a749dd7b0b91de512e01fa5202708698e0188fdfc6ac5e578f7cd9617304d03f99a7ee8a31e874270d067917042",
          "sha256": "b62f505922def8ab07ebbd36b8d047403357053d427df0e0704a1647eede8715",
          "sha1": "65ba12a4bfd28967813b089666af6f86ce5d7b43",
          "md5": "13bbac70df7da2c79b553a771286c857"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.3.0-sources.jar",
          "url": "k2o-jvm-1.3.0-sources.jar",
          "size": 38316,
          "sha512": "c4b9412ae30a3808e5627d9e468ea579e175449d285d90ea25be87f739472a4bdfbeb752d62638156231d4908c15aa29097982c1778f356c43d7f93b71ef35de",
          "sha256": "b3708c46270e288cf203dfe3e4bb55f435ecae4fe491b81567546d5ddfa2816b",
          "sha1": "9ae72deecac69b69c4a7196ec3d01ef2383eed33",
          "md5": "d9a076e01dec3b76a144436dad1783e9"
        }
      ]
    }
  ]
}
