{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-metadata-1.3.1.jar",
          "url": "k2o-1.3.1.jar",
          "size": 18421,
          "sha512": "762a105ed33e3830fe2c950718bcb31062c43e20abdb13974006d73ed629830b5f5d0160b80b113f3a9b3932ad6260ce8e8c305e724ab98886734e3ce7fa00a0",
          "sha256": "f1280127000c11570a19423bc722ba8bf87885363086baec3c5506922fdaf1ef",
          "sha1": "b69397632a87895b3196ab74e83af9c4ed5a2a61",
          "md5": "f31575d94e546f50c4e07e4fc13c5914"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "k2o-kotlin-1.3.1-sources.jar",
          "url": "k2o-1.3.1-sources.jar",
          "size": 38137,
          "sha512": "6370f00961d7db861930ff43115ed0c76e36c545755ea9aeb71b450a64057df29cd283d0826361adb671192c4c2c2df485ab7253aa7db5f8300a491f8931b886",
          "sha256": "3f61a82ae742079dfd899e594265468a059ff8e2e929a22b91ffc8e7675c32a4",
          "sha1": "3e0f81d4c0e786b7ce329606a1c6743e2cabef12",
          "md5": "0f2042c94d9537fd60670d41c3f06dbe"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../k2o-jvm/1.3.1/k2o-jvm-1.3.1.module",
        "group": "org.jraf.k2o",
        "module": "k2o-jvm",
        "version": "1.3.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../k2o-jvm/1.3.1/k2o-jvm-1.3.1.module",
        "group": "org.jraf.k2o",
        "module": "k2o-jvm",
        "version": "1.3.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../k2o-jvm/1.3.1/k2o-jvm-1.3.1.module",
        "group": "org.jraf.k2o",
        "module": "k2o-jvm",
        "version": "1.3.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.1/k2o-macosarm64-1.3.1.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.1/k2o-macosarm64-1.3.1.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.1"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.1/k2o-macosarm64-1.3.1.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../k2o-macosarm64/1.3.1/k2o-macosarm64-1.3.1.module",
        "group": "org.jraf.k2o",
        "module": "k2o-macosarm64",
        "version": "1.3.1"
      }
    }
  ]
}
