{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.0.0/k2o-1.0.0.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.0.0.jar",
          "url": "k2o-jvm-1.0.0.jar",
          "size": 66892,
          "sha512": "49bd94d42ac36f0df0aca6f175ed3a16675a492b50c26f5d4a604cda9765391b8e3afb8ccfd4a6db47fc1ed36a867de2c93d115b4d13d51b852858b0b0845c41",
          "sha256": "4d011135928c9e7b6d82bed5ad88596b641e2f718bbea55d0d9af264bf80512c",
          "sha1": "290adaa61882e1cf2aaac5e816531f3ff1a08d2c",
          "md5": "7795071550568d353ffaf692db040ef4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.0.0.jar",
          "url": "k2o-jvm-1.0.0.jar",
          "size": 66892,
          "sha512": "49bd94d42ac36f0df0aca6f175ed3a16675a492b50c26f5d4a604cda9765391b8e3afb8ccfd4a6db47fc1ed36a867de2c93d115b4d13d51b852858b0b0845c41",
          "sha256": "4d011135928c9e7b6d82bed5ad88596b641e2f718bbea55d0d9af264bf80512c",
          "sha1": "290adaa61882e1cf2aaac5e816531f3ff1a08d2c",
          "md5": "7795071550568d353ffaf692db040ef4"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.0.0-sources.jar",
          "url": "k2o-jvm-1.0.0-sources.jar",
          "size": 22382,
          "sha512": "f688c7a1ebab5a162526437149e4e3356a65f5d842454cddbc48a7a285db0bbc9778bce45fb7a8d3c69396bbeee8e4cf2b71f0b0232f633bb89daf1900097bcd",
          "sha256": "f355b5b1d50f4482c43b3209c8c31633a8d672dfabac723d03665b9458c010cf",
          "sha1": "54aaa7cb5eb8884cf46c51551b837d52ea78aa20",
          "md5": "3affcec25d1e4093ea9348dc4d7eabd4"
        }
      ]
    }
  ]
}
