{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.3.1/k2o-1.3.1.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.3.1.jar",
          "url": "k2o-jvm-1.3.1.jar",
          "size": 102627,
          "sha512": "c582f40c540a738fe799c1dc9a2765bf1efac652d899238b6af92cc3787e81cba32397d1a71bb405de07596a95e9acd7775439c8efb1f75931f8d7ff511bf3e1",
          "sha256": "c343a609b70ca3f166407aca239d3a6dea452d39249dc0b64412bd6b0c964366",
          "sha1": "ba7e3839505570661501683d220850dce443ab65",
          "md5": "c32cef6206638f6dec3130e2266d84cd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.3.1.jar",
          "url": "k2o-jvm-1.3.1.jar",
          "size": 102627,
          "sha512": "c582f40c540a738fe799c1dc9a2765bf1efac652d899238b6af92cc3787e81cba32397d1a71bb405de07596a95e9acd7775439c8efb1f75931f8d7ff511bf3e1",
          "sha256": "c343a609b70ca3f166407aca239d3a6dea452d39249dc0b64412bd6b0c964366",
          "sha1": "ba7e3839505570661501683d220850dce443ab65",
          "md5": "c32cef6206638f6dec3130e2266d84cd"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.3.1-sources.jar",
          "url": "k2o-jvm-1.3.1-sources.jar",
          "size": 38137,
          "sha512": "6370f00961d7db861930ff43115ed0c76e36c545755ea9aeb71b450a64057df29cd283d0826361adb671192c4c2c2df485ab7253aa7db5f8300a491f8931b886",
          "sha256": "3f61a82ae742079dfd899e594265468a059ff8e2e929a22b91ffc8e7675c32a4",
          "sha1": "3e0f81d4c0e786b7ce329606a1c6743e2cabef12",
          "md5": "0f2042c94d9537fd60670d41c3f06dbe"
        }
      ]
    }
  ]
}
