{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.3.0/k2o-1.3.0.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-macosArm64Main-1.3.0.klib",
          "url": "k2o-macosarm64-1.3.0.klib",
          "size": 102113,
          "sha512": "9a49e50ea4e940ea01aa5153b0ab22a010492e6d85fad13ed0da1d793c303ab2e45ebb4150ba836dc96a027076822f4de9a2b1cab3302a20b9fd73126101c59d",
          "sha256": "f88420d34521c60a417cb8c679b16625cda1d5f0206206ac01a0ffbedfaeff3e",
          "sha1": "e4fc77d43393e1dffcebbd1d3f1dcf1cecf8ca06",
          "md5": "8f1e643b41522916f944ca4a32076b03"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "k2o-macosarm64-1.3.0-sources.jar",
          "url": "k2o-macosarm64-1.3.0-sources.jar",
          "size": 38316,
          "sha512": "c4b9412ae30a3808e5627d9e468ea579e175449d285d90ea25be87f739472a4bdfbeb752d62638156231d4908c15aa29097982c1778f356c43d7f93b71ef35de",
          "sha256": "b3708c46270e288cf203dfe3e4bb55f435ecae4fe491b81567546d5ddfa2816b",
          "sha1": "9ae72deecac69b69c4a7196ec3d01ef2383eed33",
          "md5": "d9a076e01dec3b76a144436dad1783e9"
        }
      ]
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-1.3.0.kotlin_resources.zip",
          "url": "k2o-macosarm64-1.3.0-kotlin_resources.kotlin_resources.zip",
          "size": 320,
          "sha512": "aa5d83657f2f79a5740e02986572f396b1f22edde69d2635ac35bd203eb05704543333a69b22a06a775f40c6180667ab2ffe270cbef5313fab826a8efda6e38e",
          "sha256": "1a2ce1e84034808990a1d6fc181b3906239ef554bffdee1db4a527a4309d522d",
          "sha1": "4160abdb49e240bfe35779c2416e4a7d99fc1ee2",
          "md5": "83064256c0773dff74573c1f3e96feaf"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "k2o-macosarm64-1.3.0-metadata.jar",
          "url": "k2o-macosarm64-1.3.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
