{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.0.1-SNAPSHOT/k2o-1.0.1-SNAPSHOT.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.0.1-SNAPSHOT.jar",
          "url": "k2o-jvm-1.0.1-SNAPSHOT.jar",
          "size": 67674,
          "sha512": "c6b1575e84dd3d6f4487e6559420ad7dc36a9cace08aa0286a30fe111a339be6a26d42b12ef0c9350ff8ba8c1c46f61f0bd27b6988d141da47a9f9b4bfa85b69",
          "sha256": "cbfbbba706266e84bd1d68ffb5bdb2444f86cea97cd2dfeee1911f3215bb6dee",
          "sha1": "8c05a78a06e24c9ed48971bb8b4dd6bf289e45b8",
          "md5": "079ca823a66fba354941ecfa53361fe5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.0.1-SNAPSHOT.jar",
          "url": "k2o-jvm-1.0.1-SNAPSHOT.jar",
          "size": 67674,
          "sha512": "c6b1575e84dd3d6f4487e6559420ad7dc36a9cace08aa0286a30fe111a339be6a26d42b12ef0c9350ff8ba8c1c46f61f0bd27b6988d141da47a9f9b4bfa85b69",
          "sha256": "cbfbbba706266e84bd1d68ffb5bdb2444f86cea97cd2dfeee1911f3215bb6dee",
          "sha1": "8c05a78a06e24c9ed48971bb8b4dd6bf289e45b8",
          "md5": "079ca823a66fba354941ecfa53361fe5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.0.1-SNAPSHOT-sources.jar",
          "url": "k2o-jvm-1.0.1-SNAPSHOT-sources.jar",
          "size": 23718,
          "sha512": "25bc9dfc3d04d27346d1bbf05017ed0b5de51c36253a8e91b53c9015744b45615136d4b6665ccae32d6fdcdaf4b02101a1d3205ee92d9ef91a44874b04b5776f",
          "sha256": "14f88c508ea11792655c7a5e68874dc4750578309ac7808bc07f30787892911b",
          "sha1": "730750384421e2d17f5d019b5abd6b7db23148ce",
          "md5": "ade54d2d261aa14a467ec983a4b5de48"
        }
      ]
    }
  ]
}
