{
  "formatVersion": "1.1",
  "component": {
    "url": "../../k2o/1.1.1-SNAPSHOT/k2o-1.1.1-SNAPSHOT.module",
    "group": "org.jraf.k2o",
    "module": "k2o",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.1.1-SNAPSHOT.jar",
          "url": "k2o-jvm-1.1.1-SNAPSHOT.jar",
          "size": 69759,
          "sha512": "2115f52a304792c8d6ed39795ddf9ef34eb6905966572f18c3dc272cf97f318cdf98f485a75d82846c9b8e04dcd8f9f9cba0aec8e3a3f4068032c73340bdc3fc",
          "sha256": "4ae09797c887e123d731cce9a09eb5a6774c23b66987fda21c2836312d118b2b",
          "sha1": "a6b0b80f478ec46e6d722030702bd4aece084dd1",
          "md5": "1af2649a74068639be05e399317a02c8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.0.0",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "k2o-jvm-1.1.1-SNAPSHOT.jar",
          "url": "k2o-jvm-1.1.1-SNAPSHOT.jar",
          "size": 69759,
          "sha512": "2115f52a304792c8d6ed39795ddf9ef34eb6905966572f18c3dc272cf97f318cdf98f485a75d82846c9b8e04dcd8f9f9cba0aec8e3a3f4068032c73340bdc3fc",
          "sha256": "4ae09797c887e123d731cce9a09eb5a6774c23b66987fda21c2836312d118b2b",
          "sha1": "a6b0b80f478ec46e6d722030702bd4aece084dd1",
          "md5": "1af2649a74068639be05e399317a02c8"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "k2o-jvm-1.1.1-SNAPSHOT-sources.jar",
          "url": "k2o-jvm-1.1.1-SNAPSHOT-sources.jar",
          "size": 24498,
          "sha512": "d06a1463a578fe5f00abf3ffe1cd2ef8f4c20a93aa0f125953fa071dffee827475a62763199021977a0eb88b75f6f3410a06865cc36f4babb7066cbd376577a0",
          "sha256": "ced3bbe0c24d1db7d7996b044a7cf0c1b71421c51fe5f1c66f31cd5769ef9e6e",
          "sha1": "9bbda2ae3e72d68569eeb57426c8a5ca55a66807",
          "md5": "007760b462a9508dd5ff96825feaae8f"
        }
      ]
    }
  ]
}
